# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'HACKATHON2015' do
	pod 'AFNetworking', '2.0.2'
	pod 'SDWebImage', '~>3.6'
	pod 'MagicalRecord'
	pod 'JSONKit', '1.5pre'
    pod 'GoogleMaps'
    pod 'EGOTableViewPullRefresh'
    pod 'iCarousel', '~> 1.7.6'
end

target 'HACKATHON2015Tests' do

end

